### PR TITLE
BackEnd folder and README.md file with the info about the app deployment

### PR DESCRIPTION
**Pull request by zmagar**
Added BackEnd folder with README.md file with the information about Azure Static Web Apps deployment

### CODE REVIEW

**Review by OmarShehata — APPROVED** [review]
Looks great Alex!

You also mentioned you were able to set up auto deployments right? The description you have currently here is for manual deployments right?

It might be worth mentioning just briefly that auto deployments are set up via GitHub actions (assuming that's how you set it up?)

**Comment by Jaro05** [comment]
Looks great @zmagar. Thanks for providing all the helpful links!

**Comment by zmagar** [comment]
@OmarShehata During the initial deployment Azure (or GitHub) creates Azure Static Web Apps CI/CD workflow file, here is what is inside:
workflowFile
The workflow seems pretty simple and we can edit it, of course, as needed.

**Comment by OmarShehata** [comment]
Sounds great @zmagar ! I think it'd be sufficient for this doc to just add a sentence that says that the deploy happens automatically on each PR through GitHub actions, then please merge this.

**Pull request merged**
