### PR TITLE
Added icon to title bar #51

### PR DESCRIPTION
**Pull request by Jaro05**

### CODE REVIEW

**Review by OmarShehata — CHANGES_REQUESTED** [review]
Looks great @Jaro05 ! Just a couple notes:

* I think we should use the same favicon used by the Forest GEO website (https://forestgeo.si.edu/sites/all/themes/si_forestgeo/favicon/favicon.ico). I think the full logo is a bit too complicated for this small icon
* We don't need to push the `.idea/` folder to the repo here, since that contains your local VSCode setting. Try removing them from this branch, then adding `.idea/` to the `FrontEnd/.gitignore`. I think in VSCode you may need to open the `FrontEnd` folder instead of the project root

Also you should always include some description in your PR to give the reviewers context, including linking to the original issue related to this PR: https://github.com/ForestGeoHack/ForestGEO/issues/51

**Review by OmarShehata — APPROVED** [review]
Looks good! You can go ahead and merge @Jaro05

**Comment by esscott** [comment]
@OmarShehata Small detail, but would it be possible to use the ForestGEO logo (either without caption or without the text all together) instead of the general Smithsonian logo, for style consistency? I had put some instructions in my Slack message to @Jaro05 on how to make these edits to the .ai files and retain quality using an open source equivalent to Adobe Illustrator.

**Comment by OmarShehata** [comment]
@esscott yeah that sounds good to me!

**Comment by Jaro05** [comment]
@esscott I am aware that this icon is not a good fit and will fix it as soon as possible! Thank you for the feedback.

**Pull request merged**
